### ISSUE TITLE
How to call nao_gestures?

### ISSUE THREAD

**Issue by stormwolfZWA** [TomKingsfordUoA/NaoGestures#3]
Hi, 
I am trying to use your library for my thesis but ran into a problem at the last step. When I try to run: nao_gestures [/home/storm/Documents/sample.bvh][127.0.0.1]
I get the following error: nao_gestures: error: unrecognized arguments:[/home/storm/Documents/sample.bvh][127.0.0.1]

I've also tried it with the IP of my physical NAO with which I'm connect through choregraphe. How do I call nao_gestures correctly? Any help would be greatly appreciated. 

![Screenshot from 2023-05-29 23-28-01](https://github.com/TomKingsfordUoA/NaoGestures/assets/33283407/d977d1a3-9e1c-492e-9201-cc458ab6be05)

**Comment by TomKingsford** [comment]
The correct usage in your case would be `nao-gestures --bvh_file /home/storm/Documents/sample.bvh --dest_ip <nao IP> --nao_port <nao port> --my_ip <your IP> --my_port <your port>`

Notably, your IP should not be localhost (127.0.0.1) but must be the IP routable from the Nao robot (e.g. as assigned by DHCP on your router or statically assigned, depending on your network configuration).

**Comment by TomKingsford** [comment]
Alternatively, if you're using (or able to use) ROS to control your Nao, the application can publish to the `joint_angles` topic which the Nao can listen to. That's controlled with the `--use_ros` flag.

**Comment by stormwolfZWA** [comment]
Ah now I got it working, thank you for the clarification!
